export const PLANNER_CHANGE_STATIONS_NAMES = 'PLANNER_CHANGE_STATIONS_NAMES';
export const PLANNER_CHANGE_JOURNEY_OPTIONS = 'PLANNER_CHANGE_JOURNEY_OPTIONS';
export const PLANNER_CHANGE_IS_LOADING = 'PLANNER_CHANGE_IS_LOADING';
